version: '3'

tasks:
  generate:
    desc: Generate protobuf files
    dir: proto
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative *.proto
    sources:
      - proto/*.proto
    generates:
      - proto/*.pb.go
      - proto/*_grpc.pb.go

  test:
    desc: Run all tests in the project
    cmds:
      - go test ./...

  test-verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...
