// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: checker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CheckerServiceClient is the client API for CheckerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckerServiceClient interface {
	SetState(ctx context.Context, in *SetStateReq, opts ...grpc.CallOption) (*SetStateRsp, error)
	GetState(ctx context.Context, in *GetStateReq, opts ...grpc.CallOption) (*GetStateRsp, error)
	GetSLA(ctx context.Context, in *GetSLAReq, opts ...grpc.CallOption) (*GetSLAResponse, error)
}

type checkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckerServiceClient(cc grpc.ClientConnInterface) CheckerServiceClient {
	return &checkerServiceClient{cc}
}

func (c *checkerServiceClient) SetState(ctx context.Context, in *SetStateReq, opts ...grpc.CallOption) (*SetStateRsp, error) {
	out := new(SetStateRsp)
	err := c.cc.Invoke(ctx, "/checker.proto.CheckerService/SetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerServiceClient) GetState(ctx context.Context, in *GetStateReq, opts ...grpc.CallOption) (*GetStateRsp, error) {
	out := new(GetStateRsp)
	err := c.cc.Invoke(ctx, "/checker.proto.CheckerService/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkerServiceClient) GetSLA(ctx context.Context, in *GetSLAReq, opts ...grpc.CallOption) (*GetSLAResponse, error) {
	out := new(GetSLAResponse)
	err := c.cc.Invoke(ctx, "/checker.proto.CheckerService/GetSLA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckerServiceServer is the server API for CheckerService service.
// All implementations must embed UnimplementedCheckerServiceServer
// for forward compatibility
type CheckerServiceServer interface {
	SetState(context.Context, *SetStateReq) (*SetStateRsp, error)
	GetState(context.Context, *GetStateReq) (*GetStateRsp, error)
	GetSLA(context.Context, *GetSLAReq) (*GetSLAResponse, error)
	mustEmbedUnimplementedCheckerServiceServer()
}

// UnimplementedCheckerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCheckerServiceServer struct {
}

func (UnimplementedCheckerServiceServer) SetState(context.Context, *SetStateReq) (*SetStateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetState not implemented")
}
func (UnimplementedCheckerServiceServer) GetState(context.Context, *GetStateReq) (*GetStateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedCheckerServiceServer) GetSLA(context.Context, *GetSLAReq) (*GetSLAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSLA not implemented")
}
func (UnimplementedCheckerServiceServer) mustEmbedUnimplementedCheckerServiceServer() {}

// UnsafeCheckerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckerServiceServer will
// result in compilation errors.
type UnsafeCheckerServiceServer interface {
	mustEmbedUnimplementedCheckerServiceServer()
}

func RegisterCheckerServiceServer(s grpc.ServiceRegistrar, srv CheckerServiceServer) {
	s.RegisterService(&CheckerService_ServiceDesc, srv)
}

func _CheckerService_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServiceServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/checker.proto.CheckerService/SetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServiceServer).SetState(ctx, req.(*SetStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckerService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/checker.proto.CheckerService/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServiceServer).GetState(ctx, req.(*GetStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckerService_GetSLA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSLAReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerServiceServer).GetSLA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/checker.proto.CheckerService/GetSLA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerServiceServer).GetSLA(ctx, req.(*GetSLAReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckerService_ServiceDesc is the grpc.ServiceDesc for CheckerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "checker.proto.CheckerService",
	HandlerType: (*CheckerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetState",
			Handler:    _CheckerService_SetState_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _CheckerService_GetState_Handler,
		},
		{
			MethodName: "GetSLA",
			Handler:    _CheckerService_GetSLA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "checker.proto",
}
