services:
  #  Metrics collector.
  #  It scrapes targets defined in --promscrape.config
  #  And forward them to --remoteWrite.url
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.101.0
    depends_on:
      - "victoriametrics"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./vmconfigs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "-loggerFormat=json"
      - "-promscrape.config=/etc/prometheus/prometheus.yml"
      - "-remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - vm_net
    restart: unless-stopped

  # VictoriaMetrics instance, a single process responsible for
  # storing metrics and serve read requests.
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.101.0
    ports:
      - 8428:8428
    volumes:
      - vmdata:/storage
    command:
      - "-loggerFormat=json"
      - "-storageDataPath=/storage"
      - "-httpListenAddr=:8428"
    networks:
      - vm_net
    restart: unless-stopped 

  # Grafana instance configured with VictoriaMetrics as datasource
  grafana:
    container_name: grafana
    build:
      context: ./grafana
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./vmconfigs/provisioning/datasources/:/etc/grafana/provisioning/datasources
      - ./vmconfigs/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./vmconfigs/dashboards/:/var/lib/grafana/dashboards/
      - ./vmconfigs/download.sh:/download.sh
    networks:
      - vm_net
    restart: unless-stopped 
  
  example:
    container_name: example 
    build:
      dockerfile: ./dev_infra/example-checker/Dockerfile
      context: ../
    restart: unless-stopped 
    ports:
      - 13337:13337
      - 14448:14448
    networks:
      - vm_net

volumes:
  vmagentdata: {}
  vmdata: {}
  grafanadata: {}

networks:
  vm_net:
