// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingsReq) Reset() {
	*x = SetSettingsReq{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingsReq) ProtoMessage() {}

func (x *SetSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingsReq.ProtoReflect.Descriptor instead.
func (*SetSettingsReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *SetSettingsReq) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetSettingsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingsRsp) Reset() {
	*x = SetSettingsRsp{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingsRsp) ProtoMessage() {}

func (x *SetSettingsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingsRsp.ProtoReflect.Descriptor instead.
func (*SetSettingsRsp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

type GetSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsReq) Reset() {
	*x = GetSettingsReq{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsReq) ProtoMessage() {}

func (x *GetSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsReq.ProtoReflect.Descriptor instead.
func (*GetSettingsReq) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

type GetSettingsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRsp) Reset() {
	*x = GetSettingsRsp{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRsp) ProtoMessage() {}

func (x *GetSettingsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRsp.ProtoReflect.Descriptor instead.
func (*GetSettingsRsp) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetSettingsRsp) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Settings struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Services      map[string]*ServiceSettings `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *Settings) GetServices() map[string]*ServiceSettings {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceSettings struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Target        string                      `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Checkers      map[string]*CheckerSettings `protobuf:"bytes,2,rep,name=checkers,proto3" json:"checkers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sploits       map[string]*SploitSettings  `protobuf:"bytes,3,rep,name=sploits,proto3" json:"sploits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSettings) Reset() {
	*x = ServiceSettings{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSettings) ProtoMessage() {}

func (x *ServiceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSettings.ProtoReflect.Descriptor instead.
func (*ServiceSettings) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceSettings) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ServiceSettings) GetCheckers() map[string]*CheckerSettings {
	if x != nil {
		return x.Checkers
	}
	return nil
}

func (x *ServiceSettings) GetSploits() map[string]*SploitSettings {
	if x != nil {
		return x.Sploits
	}
	return nil
}

type Rate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Times         uint64                 `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"`
	Per           *durationpb.Duration   `protobuf:"bytes,2,opt,name=per,proto3" json:"per,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *Rate) GetTimes() uint64 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *Rate) GetPer() *durationpb.Duration {
	if x != nil {
		return x.Per
	}
	return nil
}

type CheckerSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         *CheckSettings         `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
	Get           *GetSettings           `protobuf:"bytes,2,opt,name=get,proto3" json:"get,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckerSettings) Reset() {
	*x = CheckerSettings{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckerSettings) ProtoMessage() {}

func (x *CheckerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckerSettings.ProtoReflect.Descriptor instead.
func (*CheckerSettings) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CheckerSettings) GetCheck() *CheckSettings {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *CheckerSettings) GetGet() *GetSettings {
	if x != nil {
		return x.Get
	}
	return nil
}

type RunOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          *Rate                  `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	MaxGoroutines int32                  `protobuf:"varint,2,opt,name=max_goroutines,json=maxGoroutines,proto3" json:"max_goroutines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunOptions) Reset() {
	*x = RunOptions{}
	mi := &file_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOptions) ProtoMessage() {}

func (x *RunOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOptions.ProtoReflect.Descriptor instead.
func (*RunOptions) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *RunOptions) GetRate() *Rate {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *RunOptions) GetMaxGoroutines() int32 {
	if x != nil {
		return x.MaxGoroutines
	}
	return 0
}

type CheckSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunOptions    *RunOptions            `protobuf:"bytes,1,opt,name=run_options,json=runOptions,proto3" json:"run_options,omitempty"`
	SuccessPoints float64                `protobuf:"fixed64,2,opt,name=success_points,json=successPoints,proto3" json:"success_points,omitempty"`
	FailPenalty   float64                `protobuf:"fixed64,3,opt,name=fail_penalty,json=failPenalty,proto3" json:"fail_penalty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSettings) Reset() {
	*x = CheckSettings{}
	mi := &file_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSettings) ProtoMessage() {}

func (x *CheckSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSettings.ProtoReflect.Descriptor instead.
func (*CheckSettings) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CheckSettings) GetRunOptions() *RunOptions {
	if x != nil {
		return x.RunOptions
	}
	return nil
}

func (x *CheckSettings) GetSuccessPoints() float64 {
	if x != nil {
		return x.SuccessPoints
	}
	return 0
}

func (x *CheckSettings) GetFailPenalty() float64 {
	if x != nil {
		return x.FailPenalty
	}
	return 0
}

type GetSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunOptions    *RunOptions            `protobuf:"bytes,1,opt,name=run_options,json=runOptions,proto3" json:"run_options,omitempty"`
	SuccessPoints float64                `protobuf:"fixed64,2,opt,name=success_points,json=successPoints,proto3" json:"success_points,omitempty"`
	FailPenalty   float64                `protobuf:"fixed64,3,opt,name=fail_penalty,json=failPenalty,proto3" json:"fail_penalty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettings) Reset() {
	*x = GetSettings{}
	mi := &file_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettings) ProtoMessage() {}

func (x *GetSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettings.ProtoReflect.Descriptor instead.
func (*GetSettings) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetSettings) GetRunOptions() *RunOptions {
	if x != nil {
		return x.RunOptions
	}
	return nil
}

func (x *GetSettings) GetSuccessPoints() float64 {
	if x != nil {
		return x.SuccessPoints
	}
	return 0
}

func (x *GetSettings) GetFailPenalty() float64 {
	if x != nil {
		return x.FailPenalty
	}
	return 0
}

type SploitSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunOptions    *RunOptions            `protobuf:"bytes,1,opt,name=run_options,json=runOptions,proto3" json:"run_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SploitSettings) Reset() {
	*x = SploitSettings{}
	mi := &file_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SploitSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SploitSettings) ProtoMessage() {}

func (x *SploitSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SploitSettings.ProtoReflect.Descriptor instead.
func (*SploitSettings) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *SploitSettings) GetRunOptions() *RunOptions {
	if x != nil {
		return x.RunOptions
	}
	return nil
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\vadmin.proto\x1a\x1egoogle/protobuf/duration.proto\"C\n" +
	"\x0eSetSettingsReq\x121\n" +
	"\bsettings\x18\x01 \x01(\v2\x15.admin.proto.SettingsR\bsettings\"\x10\n" +
	"\x0eSetSettingsRsp\"\x10\n" +
	"\x0eGetSettingsReq\"C\n" +
	"\x0eGetSettingsRsp\x121\n" +
	"\bsettings\x18\x01 \x01(\v2\x15.admin.proto.SettingsR\bsettings\"\xa6\x01\n" +
	"\bSettings\x12?\n" +
	"\bservices\x18\x01 \x03(\v2#.admin.proto.Settings.ServicesEntryR\bservices\x1aY\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.admin.proto.ServiceSettingsR\x05value:\x028\x01\"\xea\x02\n" +
	"\x0fServiceSettings\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12F\n" +
	"\bcheckers\x18\x02 \x03(\v2*.admin.proto.ServiceSettings.CheckersEntryR\bcheckers\x12C\n" +
	"\asploits\x18\x03 \x03(\v2).admin.proto.ServiceSettings.SploitsEntryR\asploits\x1aY\n" +
	"\rCheckersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.admin.proto.CheckerSettingsR\x05value:\x028\x01\x1aW\n" +
	"\fSploitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.admin.proto.SploitSettingsR\x05value:\x028\x01\"I\n" +
	"\x04Rate\x12\x14\n" +
	"\x05times\x18\x01 \x01(\x04R\x05times\x12+\n" +
	"\x03per\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03per\"o\n" +
	"\x0fCheckerSettings\x120\n" +
	"\x05check\x18\x01 \x01(\v2\x1a.admin.proto.CheckSettingsR\x05check\x12*\n" +
	"\x03get\x18\x02 \x01(\v2\x18.admin.proto.GetSettingsR\x03get\"Z\n" +
	"\n" +
	"RunOptions\x12%\n" +
	"\x04rate\x18\x01 \x01(\v2\x11.admin.proto.RateR\x04rate\x12%\n" +
	"\x0emax_goroutines\x18\x02 \x01(\x05R\rmaxGoroutines\"\x93\x01\n" +
	"\rCheckSettings\x128\n" +
	"\vrun_options\x18\x01 \x01(\v2\x17.admin.proto.RunOptionsR\n" +
	"runOptions\x12%\n" +
	"\x0esuccess_points\x18\x02 \x01(\x01R\rsuccessPoints\x12!\n" +
	"\ffail_penalty\x18\x03 \x01(\x01R\vfailPenalty\"\x91\x01\n" +
	"\vGetSettings\x128\n" +
	"\vrun_options\x18\x01 \x01(\v2\x17.admin.proto.RunOptionsR\n" +
	"runOptions\x12%\n" +
	"\x0esuccess_points\x18\x02 \x01(\x01R\rsuccessPoints\x12!\n" +
	"\ffail_penalty\x18\x03 \x01(\x01R\vfailPenalty\"J\n" +
	"\x0eSploitSettings\x128\n" +
	"\vrun_options\x18\x01 \x01(\v2\x17.admin.proto.RunOptionsR\n" +
	"runOptions2\xa0\x01\n" +
	"\fAdminService\x12G\n" +
	"\vSetSettings\x12\x1b.admin.proto.SetSettingsReq\x1a\x1b.admin.proto.SetSettingsRsp\x12G\n" +
	"\vGetSettings\x12\x1b.admin.proto.GetSettingsReq\x1a\x1b.admin.proto.GetSettingsRspB#Z!github.com/HazyCorp/govnilo/protob\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_admin_proto_goTypes = []any{
	(*SetSettingsReq)(nil),      // 0: admin.proto.SetSettingsReq
	(*SetSettingsRsp)(nil),      // 1: admin.proto.SetSettingsRsp
	(*GetSettingsReq)(nil),      // 2: admin.proto.GetSettingsReq
	(*GetSettingsRsp)(nil),      // 3: admin.proto.GetSettingsRsp
	(*Settings)(nil),            // 4: admin.proto.Settings
	(*ServiceSettings)(nil),     // 5: admin.proto.ServiceSettings
	(*Rate)(nil),                // 6: admin.proto.Rate
	(*CheckerSettings)(nil),     // 7: admin.proto.CheckerSettings
	(*RunOptions)(nil),          // 8: admin.proto.RunOptions
	(*CheckSettings)(nil),       // 9: admin.proto.CheckSettings
	(*GetSettings)(nil),         // 10: admin.proto.GetSettings
	(*SploitSettings)(nil),      // 11: admin.proto.SploitSettings
	nil,                         // 12: admin.proto.Settings.ServicesEntry
	nil,                         // 13: admin.proto.ServiceSettings.CheckersEntry
	nil,                         // 14: admin.proto.ServiceSettings.SploitsEntry
	(*durationpb.Duration)(nil), // 15: google.protobuf.Duration
}
var file_proto_admin_proto_depIdxs = []int32{
	4,  // 0: admin.proto.SetSettingsReq.settings:type_name -> admin.proto.Settings
	4,  // 1: admin.proto.GetSettingsRsp.settings:type_name -> admin.proto.Settings
	12, // 2: admin.proto.Settings.services:type_name -> admin.proto.Settings.ServicesEntry
	13, // 3: admin.proto.ServiceSettings.checkers:type_name -> admin.proto.ServiceSettings.CheckersEntry
	14, // 4: admin.proto.ServiceSettings.sploits:type_name -> admin.proto.ServiceSettings.SploitsEntry
	15, // 5: admin.proto.Rate.per:type_name -> google.protobuf.Duration
	9,  // 6: admin.proto.CheckerSettings.check:type_name -> admin.proto.CheckSettings
	10, // 7: admin.proto.CheckerSettings.get:type_name -> admin.proto.GetSettings
	6,  // 8: admin.proto.RunOptions.rate:type_name -> admin.proto.Rate
	8,  // 9: admin.proto.CheckSettings.run_options:type_name -> admin.proto.RunOptions
	8,  // 10: admin.proto.GetSettings.run_options:type_name -> admin.proto.RunOptions
	8,  // 11: admin.proto.SploitSettings.run_options:type_name -> admin.proto.RunOptions
	5,  // 12: admin.proto.Settings.ServicesEntry.value:type_name -> admin.proto.ServiceSettings
	7,  // 13: admin.proto.ServiceSettings.CheckersEntry.value:type_name -> admin.proto.CheckerSettings
	11, // 14: admin.proto.ServiceSettings.SploitsEntry.value:type_name -> admin.proto.SploitSettings
	0,  // 15: admin.proto.AdminService.SetSettings:input_type -> admin.proto.SetSettingsReq
	2,  // 16: admin.proto.AdminService.GetSettings:input_type -> admin.proto.GetSettingsReq
	1,  // 17: admin.proto.AdminService.SetSettings:output_type -> admin.proto.SetSettingsRsp
	3,  // 18: admin.proto.AdminService.GetSettings:output_type -> admin.proto.GetSettingsRsp
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
