// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingsReq) Reset() {
	*x = SetSettingsReq{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingsReq) ProtoMessage() {}

func (x *SetSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingsReq.ProtoReflect.Descriptor instead.
func (*SetSettingsReq) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *SetSettingsReq) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetSettingsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingsRsp) Reset() {
	*x = SetSettingsRsp{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingsRsp) ProtoMessage() {}

func (x *SetSettingsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingsRsp.ProtoReflect.Descriptor instead.
func (*SetSettingsRsp) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

type GetSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsReq) Reset() {
	*x = GetSettingsReq{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsReq) ProtoMessage() {}

func (x *GetSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsReq.ProtoReflect.Descriptor instead.
func (*GetSettingsReq) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

type GetSettingsRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRsp) Reset() {
	*x = GetSettingsRsp{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRsp) ProtoMessage() {}

func (x *GetSettingsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRsp.ProtoReflect.Descriptor instead.
func (*GetSettingsRsp) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetSettingsRsp) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceSettings     `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *Settings) GetServices() []*ServiceSettings {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Checkers      []*CheckerSettings     `protobuf:"bytes,3,rep,name=checkers,proto3" json:"checkers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSettings) Reset() {
	*x = ServiceSettings{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSettings) ProtoMessage() {}

func (x *ServiceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSettings.ProtoReflect.Descriptor instead.
func (*ServiceSettings) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceSettings) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ServiceSettings) GetCheckers() []*CheckerSettings {
	if x != nil {
		return x.Checkers
	}
	return nil
}

type Rate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Times         uint64                 `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"`
	Per           *durationpb.Duration   `protobuf:"bytes,2,opt,name=per,proto3" json:"per,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rate) Reset() {
	*x = Rate{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rate) ProtoMessage() {}

func (x *Rate) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rate.ProtoReflect.Descriptor instead.
func (*Rate) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

func (x *Rate) GetTimes() uint64 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *Rate) GetPer() *durationpb.Duration {
	if x != nil {
		return x.Per
	}
	return nil
}

type CheckerSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RunOptions    *RunOptions            `protobuf:"bytes,2,opt,name=run_options,json=runOptions,proto3" json:"run_options,omitempty"`
	SuccessPoints float64                `protobuf:"fixed64,3,opt,name=success_points,json=successPoints,proto3" json:"success_points,omitempty"`
	FailPenalty   float64                `protobuf:"fixed64,4,opt,name=fail_penalty,json=failPenalty,proto3" json:"fail_penalty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckerSettings) Reset() {
	*x = CheckerSettings{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckerSettings) ProtoMessage() {}

func (x *CheckerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckerSettings.ProtoReflect.Descriptor instead.
func (*CheckerSettings) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *CheckerSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckerSettings) GetRunOptions() *RunOptions {
	if x != nil {
		return x.RunOptions
	}
	return nil
}

func (x *CheckerSettings) GetSuccessPoints() float64 {
	if x != nil {
		return x.SuccessPoints
	}
	return 0
}

func (x *CheckerSettings) GetFailPenalty() float64 {
	if x != nil {
		return x.FailPenalty
	}
	return 0
}

type RunOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          *Rate                  `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	MaxGoroutines int32                  `protobuf:"varint,2,opt,name=max_goroutines,json=maxGoroutines,proto3" json:"max_goroutines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunOptions) Reset() {
	*x = RunOptions{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOptions) ProtoMessage() {}

func (x *RunOptions) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOptions.ProtoReflect.Descriptor instead.
func (*RunOptions) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *RunOptions) GetRate() *Rate {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *RunOptions) GetMaxGoroutines() int32 {
	if x != nil {
		return x.MaxGoroutines
	}
	return 0
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\vadmin.proto\x1a\x1egoogle/protobuf/duration.proto\"C\n" +
	"\x0eSetSettingsReq\x121\n" +
	"\bsettings\x18\x01 \x01(\v2\x15.admin.proto.SettingsR\bsettings\"\x10\n" +
	"\x0eSetSettingsRsp\"\x10\n" +
	"\x0eGetSettingsReq\"C\n" +
	"\x0eGetSettingsRsp\x121\n" +
	"\bsettings\x18\x01 \x01(\v2\x15.admin.proto.SettingsR\bsettings\"D\n" +
	"\bSettings\x128\n" +
	"\bservices\x18\x01 \x03(\v2\x1c.admin.proto.ServiceSettingsR\bservices\"w\n" +
	"\x0fServiceSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x128\n" +
	"\bcheckers\x18\x03 \x03(\v2\x1c.admin.proto.CheckerSettingsR\bcheckers\"I\n" +
	"\x04Rate\x12\x14\n" +
	"\x05times\x18\x01 \x01(\x04R\x05times\x12+\n" +
	"\x03per\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03per\"\xa9\x01\n" +
	"\x0fCheckerSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\vrun_options\x18\x02 \x01(\v2\x17.admin.proto.RunOptionsR\n" +
	"runOptions\x12%\n" +
	"\x0esuccess_points\x18\x03 \x01(\x01R\rsuccessPoints\x12!\n" +
	"\ffail_penalty\x18\x04 \x01(\x01R\vfailPenalty\"Z\n" +
	"\n" +
	"RunOptions\x12%\n" +
	"\x04rate\x18\x01 \x01(\v2\x11.admin.proto.RateR\x04rate\x12%\n" +
	"\x0emax_goroutines\x18\x02 \x01(\x05R\rmaxGoroutines2\xa0\x01\n" +
	"\fAdminService\x12G\n" +
	"\vSetSettings\x12\x1b.admin.proto.SetSettingsReq\x1a\x1b.admin.proto.SetSettingsRsp\x12G\n" +
	"\vGetSettings\x12\x1b.admin.proto.GetSettingsReq\x1a\x1b.admin.proto.GetSettingsRspB#Z!github.com/HazyCorp/govnilo/protob\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_admin_proto_goTypes = []any{
	(*SetSettingsReq)(nil),      // 0: admin.proto.SetSettingsReq
	(*SetSettingsRsp)(nil),      // 1: admin.proto.SetSettingsRsp
	(*GetSettingsReq)(nil),      // 2: admin.proto.GetSettingsReq
	(*GetSettingsRsp)(nil),      // 3: admin.proto.GetSettingsRsp
	(*Settings)(nil),            // 4: admin.proto.Settings
	(*ServiceSettings)(nil),     // 5: admin.proto.ServiceSettings
	(*Rate)(nil),                // 6: admin.proto.Rate
	(*CheckerSettings)(nil),     // 7: admin.proto.CheckerSettings
	(*RunOptions)(nil),          // 8: admin.proto.RunOptions
	(*durationpb.Duration)(nil), // 9: google.protobuf.Duration
}
var file_admin_proto_depIdxs = []int32{
	4, // 0: admin.proto.SetSettingsReq.settings:type_name -> admin.proto.Settings
	4, // 1: admin.proto.GetSettingsRsp.settings:type_name -> admin.proto.Settings
	5, // 2: admin.proto.Settings.services:type_name -> admin.proto.ServiceSettings
	7, // 3: admin.proto.ServiceSettings.checkers:type_name -> admin.proto.CheckerSettings
	9, // 4: admin.proto.Rate.per:type_name -> google.protobuf.Duration
	8, // 5: admin.proto.CheckerSettings.run_options:type_name -> admin.proto.RunOptions
	6, // 6: admin.proto.RunOptions.rate:type_name -> admin.proto.Rate
	0, // 7: admin.proto.AdminService.SetSettings:input_type -> admin.proto.SetSettingsReq
	2, // 8: admin.proto.AdminService.GetSettings:input_type -> admin.proto.GetSettingsReq
	1, // 9: admin.proto.AdminService.SetSettings:output_type -> admin.proto.SetSettingsRsp
	3, // 10: admin.proto.AdminService.GetSettings:output_type -> admin.proto.GetSettingsRsp
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
