version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: govnilo-redis
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --save
      - "900 1"
      - --save
      - "300 10"
      - --save
      - "60 10000"
      - --appendfsync
      - everysec
      - --aclfile
      - /usr/local/etc/redis/users.acl
    volumes:
      - redis_data:/data
      - ./redis-users.acl:/usr/local/etc/redis/users.acl:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis_data:
    driver: local
